### PR TITLE
Small refactors

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Collection of some little clean ups.

I would also recommend to limit the array parameters to only accept arrays and remove support for strings from them:
- $nfs::nfs_package
- $nfs::idmap::ldap_base

@anders-larsson what do you think about removing string support here ?

### CODE REVIEW

**Comment by anders-larsson** [comment]
Looks OK. Don't undestand why we have to put every value within quotes in YAML files though.

**Comment by anders-larsson** [comment]
Sounds good to me regarding the parameters. Didn't want to mess around with them before the first stuff was merged.

**Comment by Phil-Friderici** [comment]
> Looks OK. Don't undestand why we have to put every value within quotes in YAML files though.

Using quotes will force values to be strings :)

**Comment by Phil-Friderici** [comment]
> Sounds good to me regarding the parameters. Didn't want to mess around with them before the first stuff was merged.

Great will add this to this PR too.

**Comment by Phil-Friderici** [comment]
I think it's ready to get merged and released.

**Review by anders-larsson — APPROVED** [review]

**Pull request merged**
